# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raksha/gmsh-dealii-interface

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raksha/gmsh-dealii-interface

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raksha/gmsh-dealii-interface/CMakeFiles /home/raksha/gmsh-dealii-interface//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raksha/gmsh-dealii-interface/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bare_1d

# Build rule for target.
bare_1d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bare_1d
.PHONY : bare_1d

# fast build rule for target.
bare_1d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_1d.dir/build.make CMakeFiles/bare_1d.dir/build
.PHONY : bare_1d/fast

#=============================================================================
# Target rules for targets named laplacian_1d

# Build rule for target.
laplacian_1d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 laplacian_1d
.PHONY : laplacian_1d

# fast build rule for target.
laplacian_1d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_1d.dir/build.make CMakeFiles/laplacian_1d.dir/build
.PHONY : laplacian_1d/fast

#=============================================================================
# Target rules for targets named bare_2d

# Build rule for target.
bare_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bare_2d
.PHONY : bare_2d

# fast build rule for target.
bare_2d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_2d.dir/build.make CMakeFiles/bare_2d.dir/build
.PHONY : bare_2d/fast

#=============================================================================
# Target rules for targets named laplacian_2d

# Build rule for target.
laplacian_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 laplacian_2d
.PHONY : laplacian_2d

# fast build rule for target.
laplacian_2d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_2d.dir/build.make CMakeFiles/laplacian_2d.dir/build
.PHONY : laplacian_2d/fast

#=============================================================================
# Target rules for targets named bare_3d

# Build rule for target.
bare_3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bare_3d
.PHONY : bare_3d

# fast build rule for target.
bare_3d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_3d.dir/build.make CMakeFiles/bare_3d.dir/build
.PHONY : bare_3d/fast

#=============================================================================
# Target rules for targets named laplacian_3d

# Build rule for target.
laplacian_3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 laplacian_3d
.PHONY : laplacian_3d

# fast build rule for target.
laplacian_3d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_3d.dir/build.make CMakeFiles/laplacian_3d.dir/build
.PHONY : laplacian_3d/fast

#=============================================================================
# Target rules for targets named indent

# Build rule for target.
indent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 indent
.PHONY : indent

# fast build rule for target.
indent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indent.dir/build.make CMakeFiles/indent.dir/build
.PHONY : indent/fast

#=============================================================================
# Target rules for targets named compile_test_executables

# Build rule for target.
compile_test_executables: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile_test_executables
.PHONY : compile_test_executables

# fast build rule for target.
compile_test_executables/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/compile_test_executables.dir/build.make tests/CMakeFiles/compile_test_executables.dir/build
.PHONY : compile_test_executables/fast

#=============================================================================
# Target rules for targets named tests.inspect_parall_tria.release

# Build rule for target.
tests.inspect_parall_tria.release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.inspect_parall_tria.release
.PHONY : tests.inspect_parall_tria.release

# fast build rule for target.
tests.inspect_parall_tria.release/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.inspect_parall_tria.release.dir/build.make tests/CMakeFiles/tests.inspect_parall_tria.release.dir/build
.PHONY : tests.inspect_parall_tria.release/fast

#=============================================================================
# Target rules for targets named test_dependency.tests.inspect_parall_tria.release.executable

# Build rule for target.
test_dependency.tests.inspect_parall_tria.release.executable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dependency.tests.inspect_parall_tria.release.executable
.PHONY : test_dependency.tests.inspect_parall_tria.release.executable

# fast build rule for target.
test_dependency.tests.inspect_parall_tria.release.executable/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_dependency.tests.inspect_parall_tria.release.executable.dir/build.make tests/CMakeFiles/test_dependency.tests.inspect_parall_tria.release.executable.dir/build
.PHONY : test_dependency.tests.inspect_parall_tria.release.executable/fast

#=============================================================================
# Target rules for targets named tests.inspect_parall_tria.mpirun2.release.test

# Build rule for target.
tests.inspect_parall_tria.mpirun2.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.inspect_parall_tria.mpirun2.release.test
.PHONY : tests.inspect_parall_tria.mpirun2.release.test

# fast build rule for target.
tests.inspect_parall_tria.mpirun2.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.inspect_parall_tria.mpirun2.release.test.dir/build.make tests/CMakeFiles/tests.inspect_parall_tria.mpirun2.release.test.dir/build
.PHONY : tests.inspect_parall_tria.mpirun2.release.test/fast

#=============================================================================
# Target rules for targets named tests.load_grid_01.release

# Build rule for target.
tests.load_grid_01.release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_01.release
.PHONY : tests.load_grid_01.release

# fast build rule for target.
tests.load_grid_01.release/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_01.release.dir/build.make tests/CMakeFiles/tests.load_grid_01.release.dir/build
.PHONY : tests.load_grid_01.release/fast

#=============================================================================
# Target rules for targets named tests.load_grid_01.release.test

# Build rule for target.
tests.load_grid_01.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_01.release.test
.PHONY : tests.load_grid_01.release.test

# fast build rule for target.
tests.load_grid_01.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_01.release.test.dir/build.make tests/CMakeFiles/tests.load_grid_01.release.test.dir/build
.PHONY : tests.load_grid_01.release.test/fast

#=============================================================================
# Target rules for targets named tests.load_grid_02.release

# Build rule for target.
tests.load_grid_02.release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_02.release
.PHONY : tests.load_grid_02.release

# fast build rule for target.
tests.load_grid_02.release/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_02.release.dir/build.make tests/CMakeFiles/tests.load_grid_02.release.dir/build
.PHONY : tests.load_grid_02.release/fast

#=============================================================================
# Target rules for targets named tests.load_grid_02.release.test

# Build rule for target.
tests.load_grid_02.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_02.release.test
.PHONY : tests.load_grid_02.release.test

# fast build rule for target.
tests.load_grid_02.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_02.release.test.dir/build.make tests/CMakeFiles/tests.load_grid_02.release.test.dir/build
.PHONY : tests.load_grid_02.release.test/fast

#=============================================================================
# Target rules for targets named tests.load_grid_03.release

# Build rule for target.
tests.load_grid_03.release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_03.release
.PHONY : tests.load_grid_03.release

# fast build rule for target.
tests.load_grid_03.release/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_03.release.dir/build.make tests/CMakeFiles/tests.load_grid_03.release.dir/build
.PHONY : tests.load_grid_03.release/fast

#=============================================================================
# Target rules for targets named tests.load_grid_03.release.test

# Build rule for target.
tests.load_grid_03.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_03.release.test
.PHONY : tests.load_grid_03.release.test

# fast build rule for target.
tests.load_grid_03.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_03.release.test.dir/build.make tests/CMakeFiles/tests.load_grid_03.release.test.dir/build
.PHONY : tests.load_grid_03.release.test/fast

#=============================================================================
# Target rules for targets named tests.load_grid_parallel.release

# Build rule for target.
tests.load_grid_parallel.release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_parallel.release
.PHONY : tests.load_grid_parallel.release

# fast build rule for target.
tests.load_grid_parallel.release/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_parallel.release.dir/build.make tests/CMakeFiles/tests.load_grid_parallel.release.dir/build
.PHONY : tests.load_grid_parallel.release/fast

#=============================================================================
# Target rules for targets named test_dependency.tests.load_grid_parallel.release.executable

# Build rule for target.
test_dependency.tests.load_grid_parallel.release.executable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dependency.tests.load_grid_parallel.release.executable
.PHONY : test_dependency.tests.load_grid_parallel.release.executable

# fast build rule for target.
test_dependency.tests.load_grid_parallel.release.executable/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_dependency.tests.load_grid_parallel.release.executable.dir/build.make tests/CMakeFiles/test_dependency.tests.load_grid_parallel.release.executable.dir/build
.PHONY : test_dependency.tests.load_grid_parallel.release.executable/fast

#=============================================================================
# Target rules for targets named tests.load_grid_parallel.mpirun2.release.test

# Build rule for target.
tests.load_grid_parallel.mpirun2.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_parallel.mpirun2.release.test
.PHONY : tests.load_grid_parallel.mpirun2.release.test

# fast build rule for target.
tests.load_grid_parallel.mpirun2.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_parallel.mpirun2.release.test.dir/build.make tests/CMakeFiles/tests.load_grid_parallel.mpirun2.release.test.dir/build
.PHONY : tests.load_grid_parallel.mpirun2.release.test/fast

#=============================================================================
# Target rules for targets named tests.load_grid_parallel.release.test

# Build rule for target.
tests.load_grid_parallel.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_grid_parallel.release.test
.PHONY : tests.load_grid_parallel.release.test

# fast build rule for target.
tests.load_grid_parallel.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_grid_parallel.release.test.dir/build.make tests/CMakeFiles/tests.load_grid_parallel.release.test.dir/build
.PHONY : tests.load_grid_parallel.release.test/fast

#=============================================================================
# Target rules for targets named tests.load_unpartition_mesh.release

# Build rule for target.
tests.load_unpartition_mesh.release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_unpartition_mesh.release
.PHONY : tests.load_unpartition_mesh.release

# fast build rule for target.
tests.load_unpartition_mesh.release/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_unpartition_mesh.release.dir/build.make tests/CMakeFiles/tests.load_unpartition_mesh.release.dir/build
.PHONY : tests.load_unpartition_mesh.release/fast

#=============================================================================
# Target rules for targets named tests.load_unpartition_mesh.release.test

# Build rule for target.
tests.load_unpartition_mesh.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.load_unpartition_mesh.release.test
.PHONY : tests.load_unpartition_mesh.release.test

# fast build rule for target.
tests.load_unpartition_mesh.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.load_unpartition_mesh.release.test.dir/build.make tests/CMakeFiles/tests.load_unpartition_mesh.release.test.dir/build
.PHONY : tests.load_unpartition_mesh.release.test/fast

#=============================================================================
# Target rules for targets named tests.step-40_gmsh.release

# Build rule for target.
tests.step-40_gmsh.release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.step-40_gmsh.release
.PHONY : tests.step-40_gmsh.release

# fast build rule for target.
tests.step-40_gmsh.release/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.step-40_gmsh.release.dir/build.make tests/CMakeFiles/tests.step-40_gmsh.release.dir/build
.PHONY : tests.step-40_gmsh.release/fast

#=============================================================================
# Target rules for targets named test_dependency.tests.step-40_gmsh.release.executable

# Build rule for target.
test_dependency.tests.step-40_gmsh.release.executable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dependency.tests.step-40_gmsh.release.executable
.PHONY : test_dependency.tests.step-40_gmsh.release.executable

# fast build rule for target.
test_dependency.tests.step-40_gmsh.release.executable/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_dependency.tests.step-40_gmsh.release.executable.dir/build.make tests/CMakeFiles/test_dependency.tests.step-40_gmsh.release.executable.dir/build
.PHONY : test_dependency.tests.step-40_gmsh.release.executable/fast

#=============================================================================
# Target rules for targets named tests.step-40_gmsh.mpirun2.release.test

# Build rule for target.
tests.step-40_gmsh.mpirun2.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.step-40_gmsh.mpirun2.release.test
.PHONY : tests.step-40_gmsh.mpirun2.release.test

# fast build rule for target.
tests.step-40_gmsh.mpirun2.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.step-40_gmsh.mpirun2.release.test.dir/build.make tests/CMakeFiles/tests.step-40_gmsh.mpirun2.release.test.dir/build
.PHONY : tests.step-40_gmsh.mpirun2.release.test/fast

#=============================================================================
# Target rules for targets named tests.template.release

# Build rule for target.
tests.template.release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.template.release
.PHONY : tests.template.release

# fast build rule for target.
tests.template.release/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.template.release.dir/build.make tests/CMakeFiles/tests.template.release.dir/build
.PHONY : tests.template.release/fast

#=============================================================================
# Target rules for targets named tests.template.release.test

# Build rule for target.
tests.template.release.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.template.release.test
.PHONY : tests.template.release.test

# fast build rule for target.
tests.template.release.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.template.release.test.dir/build.make tests/CMakeFiles/tests.template.release.test.dir/build
.PHONY : tests.template.release.test/fast

#=============================================================================
# Target rules for targets named gtests

# Build rule for target.
gtests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtests
.PHONY : gtests

# fast build rule for target.
gtests/fast:
	$(MAKE) $(MAKESILENT) -f gtests/CMakeFiles/gtests.dir/build.make gtests/CMakeFiles/gtests.dir/build
.PHONY : gtests/fast

execs/laplacian.o: execs/laplacian.cc.o
.PHONY : execs/laplacian.o

# target to build an object file
execs/laplacian.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_1d.dir/build.make CMakeFiles/laplacian_1d.dir/execs/laplacian.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_2d.dir/build.make CMakeFiles/laplacian_2d.dir/execs/laplacian.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_3d.dir/build.make CMakeFiles/laplacian_3d.dir/execs/laplacian.cc.o
.PHONY : execs/laplacian.cc.o

execs/laplacian.i: execs/laplacian.cc.i
.PHONY : execs/laplacian.i

# target to preprocess a source file
execs/laplacian.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_1d.dir/build.make CMakeFiles/laplacian_1d.dir/execs/laplacian.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_2d.dir/build.make CMakeFiles/laplacian_2d.dir/execs/laplacian.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_3d.dir/build.make CMakeFiles/laplacian_3d.dir/execs/laplacian.cc.i
.PHONY : execs/laplacian.cc.i

execs/laplacian.s: execs/laplacian.cc.s
.PHONY : execs/laplacian.s

# target to generate assembly for a file
execs/laplacian.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_1d.dir/build.make CMakeFiles/laplacian_1d.dir/execs/laplacian.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_2d.dir/build.make CMakeFiles/laplacian_2d.dir/execs/laplacian.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_3d.dir/build.make CMakeFiles/laplacian_3d.dir/execs/laplacian.cc.s
.PHONY : execs/laplacian.cc.s

source/laplacian.o: source/laplacian.cc.o
.PHONY : source/laplacian.o

# target to build an object file
source/laplacian.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_1d.dir/build.make CMakeFiles/bare_1d.dir/source/laplacian.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_2d.dir/build.make CMakeFiles/bare_2d.dir/source/laplacian.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_3d.dir/build.make CMakeFiles/bare_3d.dir/source/laplacian.cc.o
.PHONY : source/laplacian.cc.o

source/laplacian.i: source/laplacian.cc.i
.PHONY : source/laplacian.i

# target to preprocess a source file
source/laplacian.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_1d.dir/build.make CMakeFiles/bare_1d.dir/source/laplacian.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_2d.dir/build.make CMakeFiles/bare_2d.dir/source/laplacian.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_3d.dir/build.make CMakeFiles/bare_3d.dir/source/laplacian.cc.i
.PHONY : source/laplacian.cc.i

source/laplacian.s: source/laplacian.cc.s
.PHONY : source/laplacian.s

# target to generate assembly for a file
source/laplacian.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_1d.dir/build.make CMakeFiles/bare_1d.dir/source/laplacian.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_2d.dir/build.make CMakeFiles/bare_2d.dir/source/laplacian.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bare_3d.dir/build.make CMakeFiles/bare_3d.dir/source/laplacian.cc.s
.PHONY : source/laplacian.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... compile_test_executables"
	@echo "... indent"
	@echo "... test_dependency.tests.inspect_parall_tria.release.executable"
	@echo "... test_dependency.tests.load_grid_parallel.release.executable"
	@echo "... test_dependency.tests.step-40_gmsh.release.executable"
	@echo "... tests.inspect_parall_tria.mpirun2.release.test"
	@echo "... tests.load_grid_01.release.test"
	@echo "... tests.load_grid_02.release.test"
	@echo "... tests.load_grid_03.release.test"
	@echo "... tests.load_grid_parallel.mpirun2.release.test"
	@echo "... tests.load_grid_parallel.release.test"
	@echo "... tests.load_unpartition_mesh.release.test"
	@echo "... tests.step-40_gmsh.mpirun2.release.test"
	@echo "... tests.template.release.test"
	@echo "... bare_1d"
	@echo "... bare_2d"
	@echo "... bare_3d"
	@echo "... gtests"
	@echo "... laplacian_1d"
	@echo "... laplacian_2d"
	@echo "... laplacian_3d"
	@echo "... tests.inspect_parall_tria.release"
	@echo "... tests.load_grid_01.release"
	@echo "... tests.load_grid_02.release"
	@echo "... tests.load_grid_03.release"
	@echo "... tests.load_grid_parallel.release"
	@echo "... tests.load_unpartition_mesh.release"
	@echo "... tests.step-40_gmsh.release"
	@echo "... tests.template.release"
	@echo "... execs/laplacian.o"
	@echo "... execs/laplacian.i"
	@echo "... execs/laplacian.s"
	@echo "... source/laplacian.o"
	@echo "... source/laplacian.i"
	@echo "... source/laplacian.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

