# CMake generated Testfile for 
# Source directory: /home/raksha/gmsh-dealii-interface/tests
# Build directory: /home/raksha/gmsh-dealii-interface/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests/load_grid_01.release "/usr/bin/cmake" "-DTRGT=tests.load_grid_01.release.test" "-DTEST=tests/load_grid_01.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_grid_01.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_01.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;5;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_grid_02.release "/usr/bin/cmake" "-DTRGT=tests.load_grid_02.release.test" "-DTEST=tests/load_grid_02.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_grid_02.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_02.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;5;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_grid_parallel.release "/usr/bin/cmake" "-DTRGT=tests.load_grid_parallel.release.test" "-DTEST=tests/load_grid_parallel.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_grid_parallel.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_parallel.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;5;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_unpartition_mesh.release "/usr/bin/cmake" "-DTRGT=tests.load_unpartition_mesh.release.test" "-DTEST=tests/load_unpartition_mesh.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_unpartition_mesh.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_unpartition_mesh.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;5;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/template.release "/usr/bin/cmake" "-DTRGT=tests.template.release.test" "-DTEST=tests/template.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/template.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/template.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;5;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(load_grid_parallel "/home/raksha/gmsh-dealii-interface/tests/load_grid_parallel")
set_tests_properties(load_grid_parallel PROPERTIES  _BACKTRACE_TRIPLES "/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;9;add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
