# CMake generated Testfile for 
# Source directory: /home/raksha/gmsh-dealii-interface/tests
# Build directory: /home/raksha/gmsh-dealii-interface/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_dependency/tests.inspect_parall_tria.release.executable "/usr/bin/cmake" "-DTRGT=test_dependency.tests.inspect_parall_tria.release.executable" "-DTEST=test_dependency/tests.inspect_parall_tria.release.executable" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(test_dependency/tests.inspect_parall_tria.release.executable PROPERTIES  FIXTURES_SETUP "test_dependency/tests.inspect_parall_tria.release.executable" LABEL "test_dependency" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/inspect_parall_tria.release/mpirun=2" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;533;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/inspect_parall_tria.mpirun=2.release "/usr/bin/cmake" "-DTRGT=tests.inspect_parall_tria.mpirun2.release.test" "-DTEST=tests/inspect_parall_tria.mpirun=2.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/inspect_parall_tria.mpirun=2.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/tests.inspect_parall_tria.release.executable" LABEL "tests" PROCESSORS "2" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/inspect_parall_tria.release/mpirun=2" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_grid_01.release "/usr/bin/cmake" "-DTRGT=tests.load_grid_01.release.test" "-DTEST=tests/load_grid_01.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_grid_01.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_01.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_grid_02.release "/usr/bin/cmake" "-DTRGT=tests.load_grid_02.release.test" "-DTEST=tests/load_grid_02.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_grid_02.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_02.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_grid_03.release "/usr/bin/cmake" "-DTRGT=tests.load_grid_03.release.test" "-DTEST=tests/load_grid_03.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_grid_03.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_03.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(test_dependency/tests.load_grid_parallel.release.executable "/usr/bin/cmake" "-DTRGT=test_dependency.tests.load_grid_parallel.release.executable" "-DTEST=test_dependency/tests.load_grid_parallel.release.executable" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(test_dependency/tests.load_grid_parallel.release.executable PROPERTIES  FIXTURES_SETUP "test_dependency/tests.load_grid_parallel.release.executable" LABEL "test_dependency" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_parallel.release/mpirun=2" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;533;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_grid_parallel.mpirun=2.release "/usr/bin/cmake" "-DTRGT=tests.load_grid_parallel.mpirun2.release.test" "-DTEST=tests/load_grid_parallel.mpirun=2.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_grid_parallel.mpirun=2.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/tests.load_grid_parallel.release.executable" LABEL "tests" PROCESSORS "2" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_parallel.release/mpirun=2" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_grid_parallel.release "/usr/bin/cmake" "-DTRGT=tests.load_grid_parallel.release.test" "-DTEST=tests/load_grid_parallel.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_grid_parallel.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_grid_parallel.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/load_unpartition_mesh.release "/usr/bin/cmake" "-DTRGT=tests.load_unpartition_mesh.release.test" "-DTEST=tests/load_unpartition_mesh.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/load_unpartition_mesh.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/load_unpartition_mesh.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(test_dependency/tests.step-40_gmsh.release.executable "/usr/bin/cmake" "-DTRGT=test_dependency.tests.step-40_gmsh.release.executable" "-DTEST=test_dependency/tests.step-40_gmsh.release.executable" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(test_dependency/tests.step-40_gmsh.release.executable PROPERTIES  FIXTURES_SETUP "test_dependency/tests.step-40_gmsh.release.executable" LABEL "test_dependency" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/step-40_gmsh.release/mpirun=2" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;533;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/step-40_gmsh.mpirun=2.release "/usr/bin/cmake" "-DTRGT=tests.step-40_gmsh.mpirun2.release.test" "-DTEST=tests/step-40_gmsh.mpirun=2.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/step-40_gmsh.mpirun=2.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/tests.step-40_gmsh.release.executable" LABEL "tests" PROCESSORS "2" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/step-40_gmsh.release/mpirun=2" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
add_test(tests/template.release "/usr/bin/cmake" "-DTRGT=tests.template.release.test" "-DTEST=tests/template.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/raksha/gmsh-dealii-interface" "-P" "/home/raksha/dealii/install/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/template.release PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/home/raksha/gmsh-dealii-interface/tests/template.release/serial" _BACKTRACE_TRIPLES "/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/home/raksha/dealii/install/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;4;DEAL_II_PICKUP_TESTS;/home/raksha/gmsh-dealii-interface/tests/CMakeLists.txt;0;")
